steps:
  - name: node
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "TOKEN_SECRET=${_TOKEN_SECRET}"
      - "FB_USER_UUID=${_FB_USER_UUID}"
      - "USER_PWD=${_USER_PWD}"
      - "FB_DATABASE_URL=${_FB_DATABASE_URL}"
      - "FB_PROJECT_ID=${_FB_PROJECT_ID}"
      - "FB_PRIVATE_KEY_ID=${_FB_PRIVATE_KEY_ID}"
      - "FB_PRIVATE_KEY=${_FB_PRIVATE_KEY}"
      - "FB_CLIENT_EMAIL=${_FB_CLIENT_EMAIL}"
      - "FB_CLIENT_ID=${_FB_CLIENT_ID}"
      - "FB_AUTH_URI=${_FB_AUTH_URI}"
      - "FB_TOKEN_URI=${_FB_TOKEN_URI}"
      - "FB_AUTH_PROVIDER_X509_CERT_URL=${_FB_AUTH_PROVIDER_X509_CERT_URL}"
      - "FB_CLIENT_X509_CERT_URL=${_FB_CLIENT_X509_CERT_URL}"
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "1600s"
